### ISSUE TITLE
Tagger does not work when adding new related record in related_records_list

### ISSUE THREAD

**Issue by malaire** [shannah/xataface-module-tagger#2]
I want to add a new related record using "New TABLENAME" button in related_records_list. This new record uses tagger to add related records to itself. In new record form I fill all values. When new record is saved its related records added with tagger are not saved.

This involves 3 main tables and 2 join tables:
TableA - this has existing record for which I want to add new related record in TableB
TableB - new related record created here, while creating it I want to add existing related record to it from TableC using tagger
TableC - existing records
TableA_TableB - joins TableA and TableB
TableB_TableC - joins TableB and TableC

When I click save I get PHP warning in apache error log:
PHP Warning:  trim() expects parameter 1 to be string, array given in XXX/modules/tagger/tagger.php on line 238, referer: XXX?-table=TableA&-action=new_related_record&-cursor=4&-skip=0&-limit=30&-mode=list&-recordid=TableA%3FTableA%3D5&-relationship=TableB

(Note: TableA also has tagger-field to add existing related records from TableB, but I can't use it here since I need to give more data than just name to create the record)

**Comment by shannah** [comment]
Can you post the relevant MySQL table definition for the table that
includes the tagger field, and the fields.ini settings for the tagger
field?

On Mon, Jan 26, 2015 at 3:17 AM, malaire notifications@github.com wrote:

> I want to add a new related record using "New TABLENAME" button in
> related_records_list. This new record uses tagger to add related records to
> itself. In new record form I fill all values. When new record is saved its
> related records added with tagger are not saved.
> 
> This involves 3 main tables and 2 join tables:
> TableA - this has existing record for which I want to add new related
> record in TableB
> TableB - new related record created here, while creating it I want to add
> existing related record to it from TableC using tagger
> TableC - existing records
> TableA_TableB - joins TableA and TableB
> TableB_TableC - joins TableB and TableC
> 
> When I click save I get PHP warning in apache error log:
> PHP Warning: trim() expects parameter 1 to be string, array given in
> XXX/modules/tagger/tagger.php on line 238, referer:
> XXX?-table=TableA&-action=new_related_record&-cursor=4&-skip=0&-limit=30&-mode=list&-recordid=TableA%3FTableA%3D5&-relationship=TableB
> 
> (Note: TableA also has tagger-field to add existing related records from
> TableB, but I can't use it here since I need to give more data than just
> name to create the record)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/shannah/xataface-module-tagger/issues/2.

## 

Steve Hannah
Web Lite Solutions Corp.

**Comment by malaire** [comment]
; TableA fields.ini
[TableB]
transient      = 1
widget:type    = tagger
relationship   = TableB
tagger_label   = Title

; TableB fields.ini
[TableC]
transient      = 1
widget:type    = tagger
relationship   = TableC
tagger_label   = Title

; SQL for all 5 tables

CREATE TABLE `TableA` (
  `TableAID` int(11) NOT NULL AUTO_INCREMENT,
  `Title` varchar(100) NOT NULL,
  PRIMARY KEY (`TableAID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TableA_TableB` (
  `TableAID` int(11) NOT NULL,
  `TableBID` int(11) NOT NULL,
  PRIMARY KEY (`TableAID`,`TableBID`),
  KEY `TableBID` (`TableBID`),
  CONSTRAINT `TableA_TableB_ibfk_1` FOREIGN KEY (`TableAID`) REFERENCES `TableA` (`TableAID`),
  CONSTRAINT `TableA_TableB_ibfk_2` FOREIGN KEY (`TableBID`) REFERENCES `TableB` (`TableBID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TableB` (
  `TableBID` int(11) NOT NULL AUTO_INCREMENT,
  `Title` varchar(100) NOT NULL,
  PRIMARY KEY (`TableBID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TableB_TableC` (
  `TableBID` int(11) NOT NULL,
  `TableCID` int(11) NOT NULL,
  PRIMARY KEY (`TableBID`,`TableCID`),
  KEY `TableCID` (`TableCID`),
  CONSTRAINT `TableB_TableC_ibfk_1` FOREIGN KEY (`TableBID`) REFERENCES `TableB` (`TableBID`),
  CONSTRAINT `TableB_TableC_ibfk_2` FOREIGN KEY (`TableCID`) REFERENCES `TableC` (`TableCID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TableC` (
  `TableCID` int(11) NOT NULL AUTO_INCREMENT,
  `Title` varchar(100) NOT NULL,
  PRIMARY KEY (`TableCID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by malaire** [comment]
In that simplified example I could actually just use tagger-field in TableA to add new related record, but in my use case it is not possible. Steps to reproduce starting from empty tables:
- create a record in TableA
- create a record in TableC
- goto TableA
- goto first record
- goto "TableB" related records tab
- click "New TableB" button
- give some Title, select existing record in TableC tagger-field
- click "Save"
- you get message "Record successfully added to TableB relationship."
  - and also PHP warning in apache log
- goto TableB and see record you just created
  - !!! it has no related records from TableC, even through one was given !!!

**Comment by malaire** [comment]
oh, and for completeness here are relationships.ini files:

; TableA relationships.ini
[TableB]
TableA_TableB.TableAID = "$TableAID"
TableA_TableB.TableBID = TableB.TableBID

; TableB relationships.ini
[TableC]
TableB_TableC.TableBID = "$TableBID"
TableB_TableC.TableCID = TableC.TableCID

**Comment by shannah** [comment]
What was the PHP warning you got in the apache log?  That might give a clue.

On Mon, Jan 26, 2015 at 9:23 AM, malaire notifications@github.com wrote:

> oh, and for completeness here are relationships.ini files:
> 
> ; TableA relationships.ini
> [TableB]
> TableA_TableB.TableAID = "$TableAID"
> TableA_TableB.TableBID = TableB.TableBID
> 
> ; TableB relationships.ini
> [TableC]
> TableB_TableC.TableBID = "$TableBID"
> TableB_TableC.TableCID = TableC.TableCID
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/shannah/xataface-module-tagger/issues/2#issuecomment-71499097
> .

## 

Steve Hannah
Web Lite Solutions Corp.

**Comment by malaire** [comment]
Warning was mentioned in my first message:
PHP Warning: trim() expects parameter 1 to be string, array given in XXX/modules/tagger/tagger.php on line 238, referer: XXX?-table=TableA&-action=new_related_record&-cursor=4&-skip=0&-limit=30&-mode=list&-recordid=TableA%3FTableA%3D5&-relationship=TableB

I don't understand why that is about relationship between TableA and TableB because that works. Problem is between TableB and TableC.

(I got same message when testing with simplified tables, only with different -cursor and -recordid)

**Comment by grillkoning** [comment]
My database does the same strange thing.
although I don't know the cause of this problem, I was able to patch it ; pls see my post in the forum on google groups
